name: ini
version: 1.1.0
author: Matthew Franglen <matthew.franglen@gmail.com>
homepage: https://github.com/matthewfranglen/dart-ini
description: Read and write .ini files

environment:
  sdk: '<3.0.0'

dev_dependencies:
  unittest: any
